services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        env_file:
            - .env
        volumes:
            - ./nginx:/etc/nginx/templates
            - ./ssl/dhparam:/etc/ssl/certs
            - ./ssl/certbot/etc:/etc/letsencrypt
            - ./ssl/certbot/var:/var/lib/letsencrypt
            - ./ssl/certbot/www:/var/www/html
        networks:
            spacequestnetwork:
                aliases:
                    - graph.spacequest.test
                    - spacequest.test
                    - graph.spacequest.link
                    - spacequest.link

    db:
        image: mongo:6
        hostname: db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
        volumes:
            - ./data/db:/data/db
            - ./scripts/database/:/docker-entrypoint-initdb.d/
        networks:
            - spacequestnetwork

    gateway:
        image: node:20
        hostname: gateway
        working_dir: /app
        volumes:
            - ./server:/app
        env_file:
            - .env
        depends_on:
            - microservice-players
            - microservice-games
        networks:
            - spacequestnetwork
        command: sh -c "exec yarn start:dev gateway"

    microservice-auth:
        image: node:20
        hostname: microservice-auth
        working_dir: /app
        volumes:
            - ./server:/app
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - spacequestnetwork
        command: sh -c "exec yarn start:dev microservice-auth"

    microservice-players:
        image: node:20
        hostname: microservice-players
        working_dir: /app
        volumes:
            - ./server:/app
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - spacequestnetwork
        command: sh -c "exec yarn start:dev microservice-players"

    microservice-games:
        image: node:20
        hostname: microservice-games
        working_dir: /app
        volumes:
            - ./server:/app
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - spacequestnetwork
        command: sh -c "exec yarn start:dev microservice-games"

    client:
        image: node:20
        hostname: client
        working_dir: /app
        volumes:
            - ./client:/app
        env_file:
            - .env
        ports:
            - 3000:3000
            - 24678:24678
        networks:
            - spacequestnetwork
        command: sh -c "rm -rf /tmp/nitro/worker-* && exec yarn dev --host=0.0.0.0"

networks:
    spacequestnetwork:
        driver: bridge
